Home/urls.py
from django.conf.urls import url
from Home.views import HomePageView,  Contact
from Home.views import about

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name="home"),
    url(r'^contact/$', Contact.as_view(), name="contact"),
    url(r'^about/$', about, name="about"),
]

achievements/urls.py
# created by Chirath R, chirath.02@gmail.com
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from achievements.views import *

urlpatterns = [

    # Articles
    url(r'^article/$', ArticleListView.as_view(), name='article'),
    url(r'^article/create/$', login_required(ArticleCreateView.as_view()), name='article_create'),
    url(r'^article/(?P<pk>[0-9]+)/$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^article/(?P<pk>[0-9]+)/update/$', login_required(ArticleUpdateView.as_view()), name='article_update'),
    url(r'^article/(?P<pk>[0-9]+)/delete/$', login_required(ArticleDeleteView.as_view()), name='article_delete'),

    # Contributions
    url(r'^contribution/$', ContributionListView.as_view(), name='contribution'),
    url(r'^contribution/create/$', login_required(ContributionCreateView.as_view()), name='contribution_create'),
    url(r'^contribution/(?P<pk>[0-9]+)/$', ContributionDetailView.as_view(), name='contribution_detail'),
    url(r'^contribution/(?P<pk>[0-9]+)/update/$', login_required(ContributionUpdateView.as_view()), name='contribution_update'),
    url(r'^contribution/(?P<pk>[0-9]+)/delete/$', login_required(ContributionDeleteView.as_view()), name='contribution_delete'),

    # GSoc
    url(r'^gsoc/$', GsocListView.as_view(), name='gsoc'),
    url(r'^gsoc/create/$', login_required(GsocCreateView.as_view()), name='gsoc_create'),
    url(r'^gsoc/(?P<pk>[0-9]+)/$', GsocDetailView.as_view(), name='gsoc_detail'),
    url(r'^gsoc/(?P<pk>[0-9]+)/update/$', login_required(GsocUpdateView.as_view()), name='gsoc_update'),
    url(r'^gsoc/(?P<pk>[0-9]+)/delete/$', login_required(GsocDeleteView.as_view()), name='gsoc_delete'),

    # Intern
    url(r'^intern/$', InternListView.as_view(), name='intern'),
    url(r'^intern/create/$', login_required(InternCreateView.as_view()), name='intern_create'),
    url(r'^intern/(?P<pk>[0-9]+)/$', InternDetailView.as_view(), name='intern_detail'),
    url(r'^intern/(?P<pk>[0-9]+)/update/$', login_required(InternUpdateView.as_view()), name='intern_update'),
    url(r'^intern/(?P<pk>[0-9]+)/delete/$', login_required(InternDeleteView.as_view()), name='intern_delete'),

    # speaker
    url(r'^speaker/$', SpeakerListView.as_view(), name='speaker'),
    url(r'^speaker/create/$', login_required(SpeakerCreateView.as_view()), name='speaker_create'),
    url(r'^speaker/(?P<pk>[0-9]+)/$', SpeakerDetailView.as_view(), name='speaker_detail'),
    url(r'^speaker/(?P<pk>[0-9]+)/update/$', login_required(SpeakerUpdateView.as_view()), name='speaker_update'),
    url(r'^speaker/(?P<pk>[0-9]+)/delete/$', login_required(SpeakerDeleteView.as_view()), name='speaker_delete'),

    # Contest
    url(r'^contest/$', ContestListView.as_view(), name='contest'),
    url(r'^contest/create/$', login_required(ContestCreateView.as_view()), name='contest_create'),
    url(r'^contest/(?P<pk>[0-9]+)/$', ContestDetailView.as_view(), name='contest_detail'),
    url(r'^contest/(?P<pk>[0-9]+)/update/$', login_required(ContestUpdateView.as_view()), name='contest_update'),
    url(r'^contest/(?P<pk>[0-9]+)/delete/$', login_required(ContestDeleteView.as_view()), name='contest_delete'),

    # all achievements
    url(r'^$', AchievementListView.as_view(), name='achievements')
]

fosswebsite/urls.py
# created by Chirath R, chirath.02@gmail.com
"""fosswebsite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import home
    2. Add a URL to urlpatterns:  url(r'^$', home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin

from fosswebsite import settings

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'accounts/', include('registration.urls')),
    path(r'accounts/', include('allauth.urls')),
    path(r'club/', include('clubManagement.urls')),
    path(r'achievements/', include('achievements.urls')),
    path(r'project/', include('projects.urls')),
    path(r'timeline/', include('timeline.urls')),
    path(r'workshop/', include('workshop.urls')),
    path(r'home/', include('Home.urls')),
    path('', include('Home.urls')),
    path(r'BlogFeedAggregator/', include('BlogFeedAggregator.urls')),
    path(r'admissions/', include('admissions.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

achievements/models.py
# -*- coding: utf-8 -*-
# created by Chirath R, chirath.02@gmail.com
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

INTERN_CHOICE = (('internship', 'Internship'),
                 ('masters', 'Masters'),
                 ('exchange_student', 'Exchange programme'))

SPEAKER_CHOICE = (('talk', ' Talk'),
                  ('demo', 'Demo'),
                  ('workshop', 'Workshop'),
                  ('paper', 'Paper Presentation'),
                  ('other', 'Other'))


class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    magazine = models.CharField(max_length=200)
    date = models.DateField()
    area = models.CharField(blank=True, max_length=300)

    def __str__(self):
        return self.user.username + " " + self.magazine

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-date',)


class Contribution(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    contribution_id = models.CharField(max_length=200)
    organisation = models.CharField(max_length=200)
    url = models.URLField()
    description = models.TextField(blank=True)
    date = models.DateField()

    def __str__(self):
        return self.user.username + ' ' + self.organisation + ' ' + self.contribution_id

    def get_absolute_url(self):
        return reverse('contribution_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-date',)


class Gsoc(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    organization = models.CharField(max_length=200)
    title = models.CharField(max_length=250)
    mentors = models.CharField(max_length=300)
    url = models.URLField(max_length=400)
    description = models.TextField(blank=True)
    date = models.DateField()

    def __str__(self):
        return self.user.username + ' ' + self.organization + ' ' + str(self.date)

    def get_absolute_url(self):
        return reverse('gsoc_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-date',)


class Intern(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    organisation = models.CharField(max_length=300)
    title = models.CharField(max_length=300)
    location = models.CharField(max_length=200)
    type = models.CharField(max_length=100, choices=INTERN_CHOICE)
    date = models.DateField()
    description = models.TextField(blank=True)

    def __str__(self):
        return self.user.username + ' ' + self.organisation

    def get_absolute_url(self):
        return reverse('intern_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-date',)


class Speaker(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    type = models.CharField(max_length=100, choices=SPEAKER_CHOICE)
    conference_name = models.CharField(max_length=200)
    location = models.CharField(max_length=300)
    url = models.URLField(blank=True)
    date = models.DateField()
    description = models.TextField(blank=True)

    def __str__(self):
        return self.user.username + " " + self.title

    def get_absolute_url(self):
        return reverse('speaker_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-date',)


class Contest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contest_id = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    url = models.URLField(blank=True)
    problems_solved = models.IntegerField()
    ranking = models.BigIntegerField()
    date = models.DateField()
    description = models.TextField(null=True)

    def __str__(self):
        return self.user.username + " " + self.title

    def get_absolute_url(self):
        return reverse('contest_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-date',)

achievements/forms.py
from django import forms

from .models import *
from bootstrap3_datetime.widgets import DateTimePicker


class ContestForm(forms.ModelForm):
    contest_id = forms.IntegerField(label='Contest id', help_text='Enter your contest id',
                                    widget=forms.NumberInput(attrs={'placeholder': 'Contest id'}))
    title = forms.CharField(label='Contest name', help_text='Enter the name of the contest',
                            widget=forms.TextInput(attrs={'placeholder': 'Contest name'}))
    url = forms.URLField(label='Contest URL', help_text='Enter URL for the contest',
                         widget=forms.URLInput(attrs={'placeholder': 'Contest URL'}))
    problems_solved = forms.IntegerField(label='Problems solved', help_text='Enter number of problems solved',
                                         widget=forms.NumberInput(attrs={'placeholder': 'problems solved'}))
    ranking = forms.IntegerField(label='Rank', help_text='Enter your rank',
                                 widget=forms.NumberInput(attrs={'placeholder': 'Rank'}))
    date = forms.DateField(label='Date of contest', widget=DateTimePicker(options={"format": "YYYY-MM-DD",
                                                                     "icons": {
                                                                         "time": "fa fa-clock-o",
                                                                         "date": "fa fa-calendar",
                                                                         "up": "fa fa-arrow-up",
                                                                         "down": "fa fa-arrow-down"
                                                                     }},
                                                            attrs={'placeholder': 'YYYY-MM-DD'}))
    description = forms.CharField(label='Description', help_text='Describe about the contest',
                                  widget=forms.Textarea(attrs={'placeholder': 'Description'}))

    def __init__(self, *args, **kwargs):
        super(ContestForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Contest
        fields = ['contest_id', 'title', 'url', 'problems_solved', 'ranking', 'date', 'description']

achievements/templates/achievements/article_confirm_delete.html
{% extends 'base/base.html' %}

{% block title %} Delete {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
        <div id="wrap">
            <div id="main">
            <!-- content goes here -->
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <form class="card" action="" method="post" >
                                <div class="card-block">
                                    {% csrf_token %}
                                    <h2>Delete {{ object.title }}?</h2>
                                    <button type="submit" class="btn btn-danger">Yes, continue</button>
                                    <a href="{% url 'team_detail' object.id %}"><button class="btn btn-info">No, take me out of here</button></a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% include 'base/footer.html' %}

    <style>
        .container {
            margin-top: 80px;
        }
    .btn {
        margin-right: 10px;
        margin-top: 20px;
    }
    </style>
{% endblock %}

achievements/templates/achievements/article_detail.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>FOSS@Amrita. Code | Share | Grow</title>

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'home/assets/images/favicon.png' %}">
    <link rel="apple-touch-icon" href="{% static 'home/assets/images/apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'home/assets/images/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'home/assets/images/apple-touch-icon-114x114.png' %}">

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,400italic,700' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'home/assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Icon Fonts -->
    <link href="{% static 'home/assets/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/et-line-font.min.css' %}" rel="stylesheet">

    <!-- Plugins -->
    <link href="{% static 'home/assets/css/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/superslides.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/vertical.min.css' %}" rel="stylesheet">

    <!-- Font awesome CDN -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Template core CSS -->
    <link href="{% static 'home/assets/css/template.css' %}" rel="stylesheet">
    <link href="{% static 'timeline/css/styles.css' %}" rel="stylesheet">

</head>
<body>

<!-- PRELOADER -->
<div class="page-loader">
    <div class="loader">Loading...</div>
</div>
<!-- /PRELOADER -->

<!-- Incudes navigation bar.  -->
{% include 'home/side-nav.html' %}

<!-- WRAPPER -->
<div class="wrapper">
     <div class="container">
                <div class="row">
                    <br>
                    <h1 class="head col-md-12"><strong>{{ object.title }}</strong></h1>
                    <hr>
                    <br>
                    <div class="col-md-10">
                        <div class="card mb-3">
                            <img class="card-img-top img-fluid" src="{% static 'achievements/image/articles-writing.jpg' %}"
                                 alt="Card image cap">
                            <div class="card-block">
                            <br>
                                <h5 class="card-text">
                                    <small class="text-muted">{{ object.area }}, {{ object.magazine }}</small>
                                </h5>
                                <p class="card-text">{{ object.description }}</p>
                                <p class="card-text">
                                    <small class="text-muted">{{ object.user.first_name }} {{ object.user.last_name }}, {{ object.date }}</small>
                                </p>
                                {% if edit_permission %}
                                    <a href="{% url 'article_update' object.id %}">
                                        <button type="submit" class="btn btn-primary add-btn">Update</button>
                                    </a>
                                    <a href="{% url 'article_delete' object.id %}">
                                        <button type="submit" class="btn btn-danger add-btn">Delete</button>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

    <!-- Footer section -->
    {% include 'home/footer.html' %}

</div>
<!-- /WRAPPER -->

<!-- JAVASCRIPT FILES -->
<script src="{% static 'home/assets/js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'home/assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.superslides.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.mb.YTPlayer.min.js' %}"></script>
<script src="{% static 'home/assets/js/imagesloaded.pkgd.js' %}"></script>
<script src="{% static 'home/assets/js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'home/assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.fitvids.js' %}"></script>
<script src="{% static 'home/assets/js/jqBootstrapValidation.js' %}"></script>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="{% static 'home/assets/js/gmap3.min.js' %}"></script>
<script src="{% static 'home/assets/js/appear.js' %}"></script>
<script src="{% static 'home/assets/js/smoothscroll.js' %}"></script>
<script src="{% static 'home/assets/js/submenu-fix.js' %}"></script>
<script src="{% static 'home/assets/js/contact.js' %}"></script>
<script src="{% static 'home/assets/js/custom.js' %}"></script>

</body>
</html>

achievements/templates/achievements/article_list.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load index %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>FOSS@Amrita. Code | Share | Grow</title>

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'home/assets/images/favicon.png' %}">
    <link rel="apple-touch-icon" href="{% static 'home/assets/images/apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'home/assets/images/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'home/assets/images/apple-touch-icon-114x114.png' %}">

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,400italic,700' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'home/assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Icon Fonts -->
    <link href="{% static 'home/assets/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/et-line-font.min.css' %}" rel="stylesheet">

    <!-- Plugins -->
    <link href="{% static 'home/assets/css/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/superslides.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/vertical.min.css' %}" rel="stylesheet">

    <!-- Font awesome CDN -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Template core CSS -->
    <link href="{% static 'home/assets/css/template.css' %}" rel="stylesheet">
    <link href="{% static 'achievements/css/table.css' %}" rel="stylesheet">

</head>
<body>

<!-- PRELOADER -->
<div class="page-loader">
    <div class="loader">Loading...</div>
</div>
<!-- /PRELOADER -->

<!-- Incudes navigation bar.  -->
{% include 'home/side-nav.html' %}

<!-- WRAPPER -->
<div class="wrapper">
    <!-- HERO -->
    <section id="hero" class="module-hero bg-dark-30"
             data-background="{% static 'BlogFeedAggregator/assets/images/mike-giles-wallpape.jpg' %}">

        <!-- HERO TEXT -->
        <div class="hero-caption">
            <div class="hero-text">
                <h1 class="hero-title font-alt">Articles</h1>
                <p class="hero-subtitle font-serif"></p>
            </div>
        </div>
        <!-- /HERO TEXT -->

    </section>
    <!-- /HERO -->
    <br><br>

    <div class="container-fluid">
        <div class="row">
                    <div class="col-md-12 table-responsive">
                        <table>
                            <thead>
                            <tr>
                                <th scope="col">Student</th>
                                <th scope="col">Magazine</th>
                                <th scope="col">Title</th>
                                <th scope="col">Area</th>
                                <th scope="col">Date</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for object in object_list %}
                                <tr class="click"
                                    onclick="window.location='{% url 'article_detail' object.id %}';">
                                    <th scope="row">{{ object.user.first_name }} {{ object.user.last_name }}</th>
                                    <td>{{ object.magazine }}</td>
                                    <td>{{ object.title }}</td>
                                    <td>{{ object.area }}</td>
                                    {% for i in range %}
                                        {% ifequal object.date.month i %}
                                            <td> {{ month|index:i }}, {{ object.date.year }}</td>
                                        {% endifequal %}
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        <hr class="divider">

        <!-- Footer section -->
        {% include 'home/footer.html' %}

    </div>
    <!-- /WRAPPER -->

    <!-- JAVASCRIPT FILES -->
    <script src="{% static 'home/assets/js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'home/assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/assets/js/jquery.superslides.min.js' %}"></script>
    <script src="{% static 'home/assets/js/jquery.mb.YTPlayer.min.js' %}"></script>
    <script src="{% static 'home/assets/js/imagesloaded.pkgd.js' %}"></script>
    <script src="{% static 'home/assets/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'home/assets/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home/assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'home/assets/js/jquery.fitvids.js' %}"></script>
    <script src="{% static 'home/assets/js/jqBootstrapValidation.js' %}"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="{% static 'home/assets/js/gmap3.min.js' %}"></script>
    <script src="{% static 'home/assets/js/appear.js' %}"></script>
    <script src="{% static 'home/assets/js/smoothscroll.js' %}"></script>
    <script src="{% static 'home/assets/js/submenu-fix.js' %}"></script>
    <script src="{% static 'home/assets/js/contact.js' %}"></script>
    <script src="{% static 'home/assets/js/custom.js' %}"></script>

</body>
</html>

achievements/templates/achievements/form.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <!-- content goes here -->
            <div class="container">
                <div class="row">
                    <div class="col-md-8 offset-md-2 card">
                        <div class="card-block">
                            <h1 class="card-title">{{ heading }}</h1>
                            <hr>
                            <form action="" method="post">
                                {% csrf_token %}
                                {% for field in form %}
                                    <div class="form-group">
                                        {% ifequal field.label 'Date of contest' %}
                                            {{ field.label_tag }}
                                            <div class='input-group date' id='datetimepicker1'>
                                                <input id="id_date" name="date" value="{{ object.date|date:'Y-M-D' }}"
                                                       type='text' placeholder="YYYY-MM-DD" class="form-control"/>
                                                <span class="input-group-addon">
                                                    <span class="fa fa-calendar"></span>
                                                </span>
                                            </div>
                                        {% else %}
                                            {{ field.label_tag }}
                                            {{ field }}
                                            <small class="form-text text-muted">
                                                {{ field.help_text }}
                                            </small>
                                        {% endifequal %}
                                    </div>
                                {% endfor %}
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'base/footer.html' %}

    <div class="notifications">
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                        {{ field.label }}: {{ error|escape }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger alert-dismissable">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <style>
        .container {
            margin-top: 70px;
        }

        .notifications {
            position: fixed;
            top: 90px;
            right: 0;
            z-index: 1000;
            font-size: 0.7em;
            max-width: 90%;
        }

        body {
            background-color: #fcfcfc;
        }
    </style>

    {% block script %}
        <script src="{% static 'base/js/jquery.min.js' %}"></script>
        <script src="{% static 'base/js/moment.min.js' %}"></script>
        <script src="{% static 'base/js/bootstrap-datetimepicker.min.js' %}"></script>
        <link href="{% static 'base/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker({
                    icons: {
                        time: "fa fa-clock-o",
                        date: "fa fa-calendar",
                        up: "fa fa-arrow-up",
                        down: "fa fa-arrow-down"
                    },
                    format: 'YYYY-MM-DD',
                    widgetPositioning: {
                        horizontal: 'right',
                        vertical: 'top'
                    }
                });
            });
        </script>
    {% endblock %}

{% endblock %}