Home/urls.py
from django.conf.urls import url
from Home.views import HomePageView,  Contact
from Home.views import about

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name="home"),
    url(r'^contact/$', Contact.as_view(), name="contact"),
    url(r'^about/$', about, name="about"),
]

clubManagement/urls.py
# created by Chirath R, chirath.02@gmail.com
from django.conf.urls import url

from clubManagement.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(
        r'^attendance-report/(?P<year>[0-9]+)/$',
        login_required(YearAttendanceReportView.as_view()),
        name='attendance_report_year_all'
    ),
    url(
        r'^attendance-report/(?P<batch>[0-9]+)/(?P<year>[0-9]+)/$',
        login_required(YearAttendanceReportView.as_view()),
        name='attendance_report_year_batch'
    ),
    url(
        r'^attendance-report/(?P<batch>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$',
        MonthAttendanceReportView.as_view(),
        name='attendance_report_month'
        ),
    url(
        r'^attendance-report-student/(?P<year>[0-9]+)/(?P<user_id>[0-9]+)/$',
        login_required(YearStudentAttendanceReportView.as_view()),
        name='attendance_report_year'
    ),
    url(
        r'^attendance/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        login_required(AttendanceAddView.as_view()),
        name='add_attendance_all'
    ),
    url(
        r'^attendance/(?P<batch>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        login_required(AttendanceAddView.as_view()),
        name='add_attendance_batch'
    ),

    # Responsibilities
    url(r'^responsibility/$', login_required(ResponsibilityListView.as_view()),
        name='responsibility'),
    url(r'^responsibility/(?P<pk>[0-9]+)/$',
        login_required(ResponsibilityDetailView.as_view()),
        name='responsibility_detail'),
    url(r'^responsibility/create/$',
        login_required(ResponsibilityCreateView.as_view()),
        name='responsibility_create'),
    url(r'^responsibility/(?P<pk>[0-9]+)/update/$',
        login_required(ResponsibilityUpdateView.as_view()),
        name='responsibility_update'),
    url(r'^responsibility/(?P<pk>[0-9]+)/delete/$',
        login_required(ResponsibilityDeleteView.as_view()),
        name='responsibility_delete'),
    url(r'^responsibility-student/(?P<pk>[0-9]+)/delete/$',
        StudentResponsibilityDeleteView.as_view(),
        name='student_responsibility_delete'
        ),

    # Teams
    url(r'^teams/$', TeamListView.as_view(), name='team'),
    url(r'^teams/(?P<pk>[0-9]+)/$', TeamDetailView.as_view(),
        name='team_detail'),
    url(r'^teams/create/$', login_required(TeamCreateView.as_view()),
        name='team_create'),
    url(r'^teams/(?P<pk>[0-9]+)/update$',
        login_required(TeamUpdateView.as_view()), name='team_update'),
    url(r'^teams/(?P<pk>[0-9]+)/delete/$',
        login_required(TeamDeleteView.as_view()), name='team_delete'),
    url(r'^teams-member/(?P<pk>[0-9]+)/delete/$',
        login_required(TeamMemberDeleteView.as_view()),
        name='team_member_delete'),

    # Status update
    url(r'^status-update/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$',
        login_required(MonthlyStatusUpdateDetailView.as_view()),
        name='monthly-status-update-detail'),
    url(r'^status-update/(?P<day>[0-9]+)/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$',
        login_required(StatusUpdateDetailView.as_view()),
        name='status-update-detail'),


    # index
    url(r'^$', login_required(IndexView.as_view()), name='club'),
]

fosswebsite/urls.py
# created by Chirath R, chirath.02@gmail.com
"""fosswebsite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import home
    2. Add a URL to urlpatterns:  url(r'^$', home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin

from fosswebsite import settings

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'accounts/', include('registration.urls')),
    path(r'accounts/', include('allauth.urls')),
    path(r'club/', include('clubManagement.urls')),
    path(r'achievements/', include('achievements.urls')),
    path(r'project/', include('projects.urls')),
    path(r'timeline/', include('timeline.urls')),
    path(r'workshop/', include('workshop.urls')),
    path(r'home/', include('Home.urls')),
    path('', include('Home.urls')),
    path(r'BlogFeedAggregator/', include('BlogFeedAggregator.urls')),
    path(r'admissions/', include('admissions.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clubManagement/models.py
# -*- coding: utf-8 -*-
# created by Chirath R, chirath.02@gmail.com
from __future__ import unicode_literals

import json

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.datetime_safe import date
from projects.models import Project
from registration.models import UserInfo


class Team(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='team/', blank=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('team_detail', kwargs={'pk': self.id})


class TeamMember(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    date_assigned = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.user.username + " - " + self.team.name


class Attendance(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                 related_name="added_by")
    date = models.DateField()
    modified_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    attendance = models.BooleanField(default=False)

    def __str__(self):
        if self.attendance:
            return self.user.username + " " + str(self.date) + " - present"
        else:
            return self.user.username + " " + str(self.date) + " - absent"


class Responsibility(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                   related_name='created_by')
    name = models.CharField(max_length=300)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('responsibility_detail', kwargs={'pk': self.pk})


class StudentResponsibility(models.Model):
    responsibility = models.ForeignKey(Responsibility, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class StatusUpdate(models.Model):
    """
    The status update for each data is stored as a string
    `user_id1 Y/N, user_id Y/N, .....`
    """
    date = models.DateField()
    value = models.CharField(max_length=1000)
    data = models.CharField(max_length=5000, blank=True)

    def get_value_dict(self):
        status_list = self.value.split(', ')
        status_dict = {}

        for status in status_list:
            user_id, status = status.split(' ')
            status_dict[int(user_id)] = status

        return status_dict

    def process_report(self):
        """
        saves a dict with key as the year and value as a list of user to the
        data field
        list-of-users = [[user, status]] where status is  a string with default
        value N
        :return:  {'year': {'name': 'full_name', 'status': 'Y'}}
        """
        status_dict = self.get_value_dict()

        # no status reports found
        if not status_dict:
            return

        start_year = date.today().year

        if date.today().month < 8:
            start_year -= 1

        user_data = {}

        for year in range(start_year, start_year - 4, -1):
            user_info_list = UserInfo.objects.filter(year=year)
            user_list = {}
            for user_info in user_info_list:
                if user_info.user.is_active and not user_info.is_mentor:
                    status = status_dict.get(int(user_info.user.pk), None)
                    if status:
                        user_list[user_info.user.get_full_name()] = status
                    else:
                        user_list[user_info.user.get_full_name()] = 'N'

            if user_list:
                user_data[str(year)] = user_list

        self.data = json.dumps(user_data)
        self.save()

    def get_report(self):
        """
        Returns a dict with {'year': {'name': 'full_name', 'status': 'Y'}}
        :return: dict
        """
        if not self.data:
            self.process_report()
        return json.loads(self.data)

    def __str__(self):
        return str(self.date)

clubManagement/templates/clubManagement/attendance_add.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>FOSS@Amrita. Code | Share | Grow</title>

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'home/assets/images/favicon.png' %}">
    <link rel="apple-touch-icon" href="{% static 'home/assets/images/apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'home/assets/images/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'home/assets/images/apple-touch-icon-114x114.png' %}">
    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,400italic,700' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700' rel='stylesheet' type='text/css'>

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,400italic,700' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'home/assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Icon Fonts -->
    <link href="{% static 'home/assets/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/et-line-font.min.css' %}" rel="stylesheet">

    <!-- Plugins -->
    <link href="{% static 'home/assets/css/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/superslides.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/vertical.min.css' %}" rel="stylesheet">

    <!-- Template core CSS -->
    <link href="{% static 'home/assets/css/template.css' %}" rel="stylesheet">
    <link href="{% static 'clubManagement/css/attendance_add.css' %}" rel="stylesheet">
</head>

<body>

<!-- PRELOADER -->
<div class="page-loader">
    <div class="loader">Loading...</div>
</div>
<!-- /PRELOADER -->

<!-- Incudes navigation bar.  -->
{% include 'home/side-nav.html' %}

<!-- WRAPPER -->
<div class="wrapper">

    <!-- HERO -->
    <section id="hero" class="module-hero bg-dark-30"
             data-background="{% static 'BlogFeedAggregator/assets/images/mike-giles-wallpape.jpg' %}">

        <!-- HERO TEXT -->
        <div class="hero-caption">
            <div class="hero-text">
                <h1 class="hero-title font-alt">Attendance</h1>
            </div>
        </div>
        <!-- /HERO TEXT -->

    </section>
    <!-- /HERO -->

    <!-- BLOG -->
    <div  class="container">
                <form class="row" action="" method="post">
                    {% csrf_token %}
                    {% for attendance in attendance_list %}
                        <br>
                        <h2 class="header col-xs-12 col-md-12">{{ attendance.1 }}</h2>
                        {% for att in attendance.0 %}
                            <div class="col-xs-6 col-sm-4 col-md-2 btn names {% if att.attendance %}btn-success{% else %}btn-danger{% endif %}"
                                    {% if request.user.is_superuser %}
                                 onclick="click_attendance('{{ att.user.username }}')" {% endif %}
                                 id="{{ att.user.username }}_div" style="white-space: normal">
                                <p class="link">{{ att.user.first_name }} {{ att.user.last_name }}</p>
                                <input type="checkbox" style="display: None" id="{{ att.user.username }}" value="True"
                                       name="{{ att.user.username }}" {% if att.attendance %}checked{% endif %}>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    <p class="col-xs-12 col-md-12"></p>
                    <div style="margin-left: 250px">
                    <button type="reset" onclick="changeDay(-1)" class="col-md-2 col-sm-6 btn btn-dark anim-scroll">Previous</button>
                    {% if request.user.is_superuser %}
                        <button type="submit" class="col-md-2 offset-md-3 col-sm-6 btn btn-dark anim-scroll">Save
                        </button>
                    {% endif %}
                    <button type="reset" onclick="changeDay(1)" class="col-md-2 offset-md-3 col-sm-6 btn btn-dark anim-scroll">Next</button>
                    </div>
                </form>
            </div>
    <!-- /BLOG -->

    <hr class="divider">


    <!-- Footer section -->
    {% include 'home/footer.html' %}

</div>
<!-- /WRAPPER -->

<!-- JAVASCRIPT FILES -->
<script src="{% static 'home/assets/js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'home/assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.superslides.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.mb.YTPlayer.min.js' %}"></script>
<script src="{% static 'home/assets/js/imagesloaded.pkgd.js' %}"></script>
<script src="{% static 'home/assets/js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'home/assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.fitvids.js' %}"></script>
<script src="{% static 'home/assets/js/jqBootstrapValidation.js' %}"></script>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="{% static 'home/assets/js/gmap3.min.js' %}"></script>
<script src="{% static 'home/assets/js/appear.js' %}"></script>
<script src="{% static 'home/assets/js/smoothscroll.js' %}"></script>
<script src="{% static 'home/assets/js/submenu-fix.js' %}"></script>
<script src="{% static 'home/assets/js/contact.js' %}"></script>
<script src="{% static 'home/assets/js/custom.js' %}"></script>
<script src="{% static 'clubManagement/js/attendance.js' %}"></script>

<script>
        function changeDay(i) {
            var variables, year, month, day, link, date;

            variables = window.location.href.split("/");

            year = variables[(variables.length - 4)];
            month = variables[variables.length - 3] - 1;
            day = variables[variables.length - 2];

            if (variables.length === 9)
                link = '/club/attendance/';
            else
                link = '/club/attendance/' + parseInt(variables[variables.length - 5]) + '/';

            date = new Date(year, month, day, 0, 0, 0);
            date.setDate(date.getDate() + i);
            link += date.getFullYear() + '/' + (date.getMonth() + 1) + '/' + date.getDate();

            window.location = link;
        }
</script>

</body>

</html>

clubManagement/templates/clubManagement/attendance_add_batch.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Add attendance {% endblock %}

{% block body %}
    {% include 'base/nav-bar.html' %}
    <div id="wrap">
        <div id="main">
            <div class="container">
                <form class="row" action="" method="post">
                {% csrf_token %}
                    {% for attendance in attendance_list %}
                        <h2 class="header col-xs-12 col-md-12">{{ attendance.1 }}</h2>
                        {% for att in attendance.0 %}
                            <div class="col-xs-6 col-sm-4 col-md-2 btn names {% if att.attendance %}btn-success{% else %}btn-danger{% endif %}" {% if request.user.is_superuser %} onclick="click_attendance('{{ att.user.username }}')" {% endif %} id="{{ att.user.username }}_div">
                                <p>{{ att.user.first_name }} {{ att.user.last_name }}</p>
                                <input type="checkbox" style="display: None" id="{{ att.user.username }}" value="True" name="{{ att.user.username }}" {% if att.attendance %}checked{% endif %}>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    <p class="col-xs-12 col-md-12"></p>
                    <button type="reset" onclick="changeDay(-1)" class="col-md-2 col-sm-6 btn">Previous</button>
                    {% if request.user.is_superuser %}
                    <button type="submit" class="col-md-2 offset-md-3 col-sm-6 btn btn-primary save-btn">Save</button>
                    {% endif %}
                    <button type="reset" onclick="changeDay(1)" class="col-md-2 offset-md-3 col-sm-6 btn">Next</button>
                </form>
            </div>
        </div>
    </div>

    {% include 'base/footer.html' %}

    <script>
        function changeDay(i) {
            var variables = window.location.href.split("/");

            var batch = parseInt(variables[5]);
            var year = parseInt(variables[6]);
            var month = parseInt(variables[7]) - 1;
            var day = parseInt(variables[8]);

            console.log(batch , year , month , day);

            var link = '/club/attendance/' + batch + '/';

            var date = new Date(year , month , day , 0 , 0 , 0);
            date.setDate(date.getDate() + i);
            console.log(batch , year , month , day);

            link += date.getFullYear() + '/' + (date.getMonth() + 1) + '/' + date.getDate();

            window.location = link;
        }
    </script>

    <style>
        .btn {
            margin: 10px;
        }

        .save-btn {
            padding: 10px 0;
        }

        .names {
            height: 80px;
        }

        .names p {
            margin: 16px 0;
        }

        form {
            margin: 30px 0;
        }
        .header {
            padding-top: 20px;
            text-align: center;
        }
    </style>

    {% block script %}
        <script src="{% static 'clubManagement/js/attendance.js' %}"></script>
    {% endblock %}
{% endblock %}

clubManagement/templates/clubManagement/attendance_daily.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>FOSS@Amrita. Code | Share | Grow</title>

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'home/assets/images/favicon.png' %}">
    <link rel="apple-touch-icon" href="{% static 'home/assets/images/apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'home/assets/images/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'home/assets/images/apple-touch-icon-114x114.png' %}">
    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,400italic,700' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700' rel='stylesheet' type='text/css'>

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,400italic,700' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700' rel='stylesheet' type='text/css'>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'home/assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Icon Fonts -->
    <link href="{% static 'home/assets/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/et-line-font.min.css' %}" rel="stylesheet">

    <!-- Plugins -->
    <link href="{% static 'home/assets/css/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/superslides.css' %}" rel="stylesheet">
    <link href="{% static 'home/assets/css/vertical.min.css' %}" rel="stylesheet">

    <!-- Template core CSS -->
    <link href="{% static 'home/assets/css/template.css' %}" rel="stylesheet">
</head>

<body>

<!-- PRELOADER -->
<div class="page-loader">
    <div class="loader">Loading...</div>
</div>
<!-- /PRELOADER -->

<!-- Incudes navigation bar.  -->
{% include 'home/side-nav.html' %}

<!-- WRAPPER -->
<div class="wrapper">

    <!-- HERO -->
    <section id="hero" class="module-hero bg-dark-30"
             data-background="{% static 'BlogFeedAggregator/assets/images/mike-giles-wallpape.jpg' %}">

        <!-- HERO TEXT -->
        <div class="hero-caption">
            <div class="hero-text">
                <h1 class="hero-title font-alt">Attendance</h1>
                <p class="hero-subtitle font-serif"></p>
            </div>
        </div>
        <!-- /HERO TEXT -->

    </section>
    <!-- /HERO -->

    <!-- BLOG -->
    <br><br>
    <div class="container" align="center">
        <h2 class="header">{{ head }}</h2>
        <div class="row form">
            {% csrf_token %}
            {% for att in attendance_list %}
                <div class="col-xs-6 col-sm-4 col-md-2 btn names {% if att.attendance %}btn-success{% else %}btn-danger{% endif %}"
                     id="{{ att.user.username }}_div" style="white-space: normal">
                    <p class="link">{{ att.user.first_name }} {{ att.user.last_name }}</p>
                </div>
            {% endfor %}
            <p class="col-xs-12 col-md-12"></p>
        </div>
    </div>
    <!-- /BLOG -->

    <hr class="divider">


    <!-- Footer section -->
    {% include 'home/footer.html' %}

</div>
<!-- /WRAPPER -->

<!-- JAVASCRIPT FILES -->
<script src="{% static 'home/assets/js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'home/assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.superslides.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.mb.YTPlayer.min.js' %}"></script>
<script src="{% static 'home/assets/js/imagesloaded.pkgd.js' %}"></script>
<script src="{% static 'home/assets/js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'home/assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'home/assets/js/jquery.fitvids.js' %}"></script>
<script src="{% static 'home/assets/js/jqBootstrapValidation.js' %}"></script>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="{% static 'home/assets/js/gmap3.min.js' %}"></script>
<script src="{% static 'home/assets/js/appear.js' %}"></script>
<script src="{% static 'home/assets/js/smoothscroll.js' %}"></script>
<script src="{% static 'home/assets/js/submenu-fix.js' %}"></script>
<script src="{% static 'home/assets/js/contact.js' %}"></script>
<script src="{% static 'home/assets/js/custom.js' %}"></script>

<script src="{% static 'clubManagement/js/attendance.js' %}"></script>

</body>

</html>

clubManagement/templates/clubManagement/attendance_yearly.html
{% extends 'base/base.html' %}
{% load static %}
{% load index %}
{% block content %}
    <!-- HERO -->
    <section id="hero" class="module-hero bg-dark-30"
             data-background="{% static 'BlogFeedAggregator/assets/images/mike-giles-wallpape.jpg' %}">

        <!-- HERO TEXT -->
        <div class="hero-caption">
            <div class="hero-text">
                <h1 class="hero-title font-alt">Attendance</h1>
                <p class="hero-subtitle font-serif"></p>
            </div>
        </div>
        <!-- /HERO TEXT -->

    </section>
    <!-- /HERO -->

    <!-- BLOG -->


    <div class="container graph-div">
        <div class="row">
            {% if errors %}
                <div class="col-md-12">
                    <div class="alert alert-danger" role="alert">
                        <strong>Oh snap!</strong> {{ errors }}
                    </div>
                </div>
            {% else %}
                <div class="col-md-10">
                    <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                    <hr>
                    <canvas id="myChart" width="400" height="400"></canvas>
                </div>
                <div class="col-md-2">
                    <div class="col-md-12">
                        <h2>{{ year }}</h2>
                    </div>
                    <hr>
                    {% for i in month_num %}
                        <div class="col-md-12">
                            <p>{{ month|index:i }} - {{ month_att|index:i }}</p>
                        </div>
                    {% endfor %}
                </div>

            {% endif %}
    </div>
    </div>
{% endblock %}
{% block script %}
<script src="{% static 'base/js/chart-bundle.js'%}"></script>

<script>

    window.chartColors = {
        red: 'rgb(255, 99, 132)',
        orange: 'rgb(255, 159, 64)',
        yellow: 'rgb(255, 205, 86)',
        green: 'rgb(75, 192, 192)',
        blue: 'rgb(54, 162, 235)',
        purple: 'rgb(153, 102, 255)',
        grey: 'rgb(201, 203, 207)'
    };

    var MONTHS = [
        {% for i in month %}
            '{{ i }}',
        {% endfor %}
    ];
    var config = {
        type: 'line',
        data: {
            labels: MONTHS,
            datasets: [{
                label: "{{ user.first_name }} {{ user.last_name }}",
                backgroundColor: window.chartColors.blue,
                borderColor: window.chartColors.blue,
                data: [
                    {% for i in month_att %}
                        {{ i }},
                    {% endfor %}
                ],
                fill: false,
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            title: {
                display: true,
                text: 'Attendance report'
            },
            tooltips: {
                mode: 'index',
                intersect: false,
            },
            hover: {
                mode: 'nearest',
                intersect: true
            },
            scales: {
                xAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Months'
                    }
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Number of days'
                    }
                }]
            }
        }
    };

    window.onload = function () {
        var ctx = document.getElementById("myChart").getContext("2d");
        window.myLine = new Chart(ctx, config);
    };

</script>
<style>
    .graph-div {
        margin-top: 40px;
    }
    canvas {
        max-height: 500px;
    }
</style>
{% endblock %}